// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsBovaAKI-uvTyrHjjZ3ZJji293v4vAo',
    appId: '1:132791364912:web:aedbf49fc056781b222cf5',
    messagingSenderId: '132791364912',
    projectId: 'cooking-app-e5925',
    authDomain: 'cooking-app-e5925.firebaseapp.com',
    storageBucket: 'cooking-app-e5925.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJduxi1dFaPWS1q1iJXkUr89_cQxD0EA',
    appId: '1:132791364912:android:662fe034862aed40222cf5',
    messagingSenderId: '132791364912',
    projectId: 'cooking-app-e5925',
    storageBucket: 'cooking-app-e5925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXII5otziDgh8QE14JGQuhd5wU3KFsyrM',
    appId: '1:132791364912:ios:b65e0d01571a6b39222cf5',
    messagingSenderId: '132791364912',
    projectId: 'cooking-app-e5925',
    storageBucket: 'cooking-app-e5925.appspot.com',
    androidClientId: '132791364912-h64c82884fptoldf83d014qjgvvao9jv.apps.googleusercontent.com',
    iosClientId: '132791364912-pf6kbmrk98ade94jkda42qcutcuue4pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXII5otziDgh8QE14JGQuhd5wU3KFsyrM',
    appId: '1:132791364912:ios:b65e0d01571a6b39222cf5',
    messagingSenderId: '132791364912',
    projectId: 'cooking-app-e5925',
    storageBucket: 'cooking-app-e5925.appspot.com',
    androidClientId: '132791364912-h64c82884fptoldf83d014qjgvvao9jv.apps.googleusercontent.com',
    iosClientId: '132791364912-pf6kbmrk98ade94jkda42qcutcuue4pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
